[versions]

# Kotlin
ktor = "2.2.4"
kotlin = "1.8.20"
exposed = "0.40.1"

[libraries]

# Discord
jda = { module = "net.dv8tion:JDA", version = "5.0.0-beta.9" }

configme = { module = "ch.jalu:configme", version = "1.3.0" }

gson = { module = "com.google.code.gson:gson", version = "2.10.1" }

dotenv = { module = "io.github.cdimascio:dotenv-kotlin", version = "6.4.1" }
logback = { module = "ch.qos.logback:logback-classic", version = "1.4.5" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }